/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseDisputeStatisticsDTO } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
/**
 * DisputeStatisticsApi - axios parameter creator
 * @export
 */
export const DisputeStatisticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get comprehensive dispute statistics (admin only)
         * @summary Get dispute statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatistics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/disputes/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DisputeStatisticsApi - functional programming interface
 * @export
 */
export const DisputeStatisticsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DisputeStatisticsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get comprehensive dispute statistics (admin only)
         * @summary Get dispute statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatistics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseDisputeStatisticsDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatistics(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DisputeStatisticsApi.getStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DisputeStatisticsApi - factory interface
 * @export
 */
export const DisputeStatisticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DisputeStatisticsApiFp(configuration)
    return {
        /**
         * Get comprehensive dispute statistics (admin only)
         * @summary Get dispute statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatistics(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDisputeStatisticsDTO> {
            return localVarFp.getStatistics(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DisputeStatisticsApi - interface
 * @export
 * @interface DisputeStatisticsApi
 */
export interface DisputeStatisticsApiInterface {
    /**
     * Get comprehensive dispute statistics (admin only)
     * @summary Get dispute statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisputeStatisticsApiInterface
     */
    getStatistics(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDisputeStatisticsDTO>;

}

/**
 * DisputeStatisticsApi - object-oriented interface
 * @export
 * @class DisputeStatisticsApi
 * @extends {BaseAPI}
 */
export class DisputeStatisticsApi extends BaseAPI implements DisputeStatisticsApiInterface {
    /**
     * Get comprehensive dispute statistics (admin only)
     * @summary Get dispute statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DisputeStatisticsApi
     */
    public getStatistics(options?: RawAxiosRequestConfig) {
        return DisputeStatisticsApiFp(this.configuration).getStatistics(options).then((request) => request(this.axios, this.basePath));
    }
}

