/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 审计日志筛选请求参数
 * @export
 * @interface AuditLogFilterRequest
 */
export interface AuditLogFilterRequest {
    /**
     * 搜索关键词
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'keyword'?: string;
    /**
     * 页码（从 0 开始）
     * @type {number}
     * @memberof AuditLogFilterRequest
     */
    'page'?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof AuditLogFilterRequest
     */
    'size'?: number;
    /**
     * 排序字段
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'sortBy'?: string;
    /**
     * 排序方向
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'sortDirection'?: AuditLogFilterRequestSortDirectionEnum;
    /**
     * 开始时间
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'startTime'?: string;
    /**
     * 结束时间
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'endTime'?: string;
    /**
     * 操作人ID
     * @type {number}
     * @memberof AuditLogFilterRequest
     */
    'operatorId'?: number;
    /**
     * 操作类型（CREATE/UPDATE/DELETE/APPROVE等）
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'actionType'?: AuditLogFilterRequestActionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'sortByOrDefault'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuditLogFilterRequest
     */
    'sizeOrDefault'?: number;
    /**
     * 
     * @type {number}
     * @memberof AuditLogFilterRequest
     */
    'pageOrDefault'?: number;
    /**
     * 
     * @type {string}
     * @memberof AuditLogFilterRequest
     */
    'sortDirectionOrDefault'?: string;
}

export const AuditLogFilterRequestSortDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;

export type AuditLogFilterRequestSortDirectionEnum = typeof AuditLogFilterRequestSortDirectionEnum[keyof typeof AuditLogFilterRequestSortDirectionEnum];
export const AuditLogFilterRequestActionTypeEnum = {
    UserLogin: 'USER_LOGIN',
    UserRegister: 'USER_REGISTER',
    UserBan: 'USER_BAN',
    UserUnban: 'USER_UNBAN',
    GoodsCreate: 'GOODS_CREATE',
    GoodsApprove: 'GOODS_APPROVE',
    GoodsDelete: 'GOODS_DELETE',
    PostCreate: 'POST_CREATE',
    PostApprove: 'POST_APPROVE',
    PostDelete: 'POST_DELETE',
    ReplyCreate: 'REPLY_CREATE',
    ReplyDelete: 'REPLY_DELETE',
    OrderCreate: 'ORDER_CREATE',
    OrderPay: 'ORDER_PAY',
    OrderCancel: 'ORDER_CANCEL',
    DisputeCreate: 'DISPUTE_CREATE',
    DisputeUpdate: 'DISPUTE_UPDATE',
    DisputeClose: 'DISPUTE_CLOSE',
    ReportCreate: 'REPORT_CREATE',
    ReportHandle: 'REPORT_HANDLE',
    UserAppeal: 'USER_APPEAL',
    AppealApprove: 'APPEAL_APPROVE',
    AppealReject: 'APPEAL_REJECT',
    AppealCancel: 'APPEAL_CANCEL',
    ComplianceCheck: 'COMPLIANCE_CHECK',
    NotificationFail: 'NOTIFICATION_FAIL',
    Update: 'UPDATE',
    Delete: 'DELETE'
} as const;

export type AuditLogFilterRequestActionTypeEnum = typeof AuditLogFilterRequestActionTypeEnum[keyof typeof AuditLogFilterRequestActionTypeEnum];


