/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DisputeDTO
 */
export interface DisputeDTO {
    /**
     * 
     * @type {number}
     * @memberof DisputeDTO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'disputeCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof DisputeDTO
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'orderNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof DisputeDTO
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof DisputeDTO
     */
    'initiatorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'initiatorNickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'initiatorRole'?: DisputeDTOInitiatorRoleEnum;
    /**
     * 
     * @type {number}
     * @memberof DisputeDTO
     */
    'respondentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'respondentNickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'disputeType'?: DisputeDTODisputeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'descriptionSummary'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'status'?: DisputeDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'negotiationDeadline'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'arbitrationDeadline'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'arbitrationResult'?: DisputeDTOArbitrationResultEnum;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DisputeDTO
     */
    'completed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DisputeDTO
     */
    'negotiating'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DisputeDTO
     */
    'arbitrating'?: boolean;
}

export const DisputeDTOInitiatorRoleEnum = {
    Buyer: 'BUYER',
    Seller: 'SELLER'
} as const;

export type DisputeDTOInitiatorRoleEnum = typeof DisputeDTOInitiatorRoleEnum[keyof typeof DisputeDTOInitiatorRoleEnum];
export const DisputeDTODisputeTypeEnum = {
    GoodsMismatch: 'GOODS_MISMATCH',
    QualityIssue: 'QUALITY_ISSUE',
    LogisticsDelay: 'LOGISTICS_DELAY',
    FalseAdvertising: 'FALSE_ADVERTISING',
    Other: 'OTHER'
} as const;

export type DisputeDTODisputeTypeEnum = typeof DisputeDTODisputeTypeEnum[keyof typeof DisputeDTODisputeTypeEnum];
export const DisputeDTOStatusEnum = {
    Submitted: 'SUBMITTED',
    Negotiating: 'NEGOTIATING',
    PendingArbitration: 'PENDING_ARBITRATION',
    Arbitrating: 'ARBITRATING',
    Completed: 'COMPLETED',
    Closed: 'CLOSED'
} as const;

export type DisputeDTOStatusEnum = typeof DisputeDTOStatusEnum[keyof typeof DisputeDTOStatusEnum];
export const DisputeDTOArbitrationResultEnum = {
    FullRefund: 'FULL_REFUND',
    PartialRefund: 'PARTIAL_REFUND',
    Reject: 'REJECT',
    NeedMoreEvidence: 'NEED_MORE_EVIDENCE'
} as const;

export type DisputeDTOArbitrationResultEnum = typeof DisputeDTOArbitrationResultEnum[keyof typeof DisputeDTOArbitrationResultEnum];


