/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArbitrationDTO } from './arbitration-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { EvidenceDTO } from './evidence-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { NegotiationMessageDTO } from './negotiation-message-dto';

/**
 * 业务数据载荷
 * @export
 * @interface DisputeDetailDTO
 */
export interface DisputeDetailDTO {
    /**
     * 
     * @type {number}
     * @memberof DisputeDetailDTO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'disputeCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof DisputeDetailDTO
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'orderNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof DisputeDetailDTO
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof DisputeDetailDTO
     */
    'initiatorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'initiatorNickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'initiatorRole'?: DisputeDetailDTOInitiatorRoleEnum;
    /**
     * 
     * @type {number}
     * @memberof DisputeDetailDTO
     */
    'respondentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'respondentNickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'disputeType'?: DisputeDetailDTODisputeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'status'?: DisputeDetailDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'negotiationDeadline'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'arbitrationDeadline'?: string;
    /**
     * 
     * @type {number}
     * @memberof DisputeDetailDTO
     */
    'arbitratorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'arbitratorNickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'arbitrationResult'?: DisputeDetailDTOArbitrationResultEnum;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'completedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'closedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'closeReason'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeDetailDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<EvidenceDTO>}
     * @memberof DisputeDetailDTO
     */
    'evidences'?: Array<EvidenceDTO>;
    /**
     * 
     * @type {Array<NegotiationMessageDTO>}
     * @memberof DisputeDetailDTO
     */
    'negotiations'?: Array<NegotiationMessageDTO>;
    /**
     * 
     * @type {ArbitrationDTO}
     * @memberof DisputeDetailDTO
     */
    'arbitration'?: ArbitrationDTO;
}

export const DisputeDetailDTOInitiatorRoleEnum = {
    Buyer: 'BUYER',
    Seller: 'SELLER'
} as const;

export type DisputeDetailDTOInitiatorRoleEnum = typeof DisputeDetailDTOInitiatorRoleEnum[keyof typeof DisputeDetailDTOInitiatorRoleEnum];
export const DisputeDetailDTODisputeTypeEnum = {
    GoodsMismatch: 'GOODS_MISMATCH',
    QualityIssue: 'QUALITY_ISSUE',
    LogisticsDelay: 'LOGISTICS_DELAY',
    FalseAdvertising: 'FALSE_ADVERTISING',
    Other: 'OTHER'
} as const;

export type DisputeDetailDTODisputeTypeEnum = typeof DisputeDetailDTODisputeTypeEnum[keyof typeof DisputeDetailDTODisputeTypeEnum];
export const DisputeDetailDTOStatusEnum = {
    Submitted: 'SUBMITTED',
    Negotiating: 'NEGOTIATING',
    PendingArbitration: 'PENDING_ARBITRATION',
    Arbitrating: 'ARBITRATING',
    Completed: 'COMPLETED',
    Closed: 'CLOSED'
} as const;

export type DisputeDetailDTOStatusEnum = typeof DisputeDetailDTOStatusEnum[keyof typeof DisputeDetailDTOStatusEnum];
export const DisputeDetailDTOArbitrationResultEnum = {
    FullRefund: 'FULL_REFUND',
    PartialRefund: 'PARTIAL_REFUND',
    Reject: 'REJECT',
    NeedMoreEvidence: 'NEED_MORE_EVIDENCE'
} as const;

export type DisputeDetailDTOArbitrationResultEnum = typeof DisputeDetailDTOArbitrationResultEnum[keyof typeof DisputeDetailDTOArbitrationResultEnum];


