/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 纠纷筛选请求参数
 * @export
 * @interface DisputeFilterRequest
 */
export interface DisputeFilterRequest {
    /**
     * 搜索关键词
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'keyword'?: string;
    /**
     * 页码（从 0 开始）
     * @type {number}
     * @memberof DisputeFilterRequest
     */
    'page'?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof DisputeFilterRequest
     */
    'size'?: number;
    /**
     * 排序字段
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'sortBy'?: string;
    /**
     * 排序方向
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'sortDirection'?: DisputeFilterRequestSortDirectionEnum;
    /**
     * 开始时间
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'startTime'?: string;
    /**
     * 结束时间
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'endTime'?: string;
    /**
     * 纠纷类型（REFUND/QUALITY/DELIVERY/OTHER）
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'disputeType'?: DisputeFilterRequestDisputeTypeEnum;
    /**
     * 纠纷状态（NEGOTIATING/PENDING_ARBITRATION/ARBITRATING/RESOLVED/CANCELLED）
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'status'?: DisputeFilterRequestStatusEnum;
    /**
     * 仲裁员ID
     * @type {number}
     * @memberof DisputeFilterRequest
     */
    'arbitratorId'?: number;
    /**
     * 最小金额
     * @type {number}
     * @memberof DisputeFilterRequest
     */
    'minAmount'?: number;
    /**
     * 最大金额
     * @type {number}
     * @memberof DisputeFilterRequest
     */
    'maxAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof DisputeFilterRequest
     */
    'pageOrDefault'?: number;
    /**
     * 
     * @type {number}
     * @memberof DisputeFilterRequest
     */
    'sizeOrDefault'?: number;
    /**
     * 
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'sortDirectionOrDefault'?: string;
    /**
     * 
     * @type {string}
     * @memberof DisputeFilterRequest
     */
    'sortByOrDefault'?: string;
}

export const DisputeFilterRequestSortDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;

export type DisputeFilterRequestSortDirectionEnum = typeof DisputeFilterRequestSortDirectionEnum[keyof typeof DisputeFilterRequestSortDirectionEnum];
export const DisputeFilterRequestDisputeTypeEnum = {
    GoodsMismatch: 'GOODS_MISMATCH',
    QualityIssue: 'QUALITY_ISSUE',
    LogisticsDelay: 'LOGISTICS_DELAY',
    FalseAdvertising: 'FALSE_ADVERTISING',
    Other: 'OTHER'
} as const;

export type DisputeFilterRequestDisputeTypeEnum = typeof DisputeFilterRequestDisputeTypeEnum[keyof typeof DisputeFilterRequestDisputeTypeEnum];
export const DisputeFilterRequestStatusEnum = {
    Submitted: 'SUBMITTED',
    Negotiating: 'NEGOTIATING',
    PendingArbitration: 'PENDING_ARBITRATION',
    Arbitrating: 'ARBITRATING',
    Completed: 'COMPLETED',
    Closed: 'CLOSED'
} as const;

export type DisputeFilterRequestStatusEnum = typeof DisputeFilterRequestStatusEnum[keyof typeof DisputeFilterRequestStatusEnum];


