/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 业务数据载荷
 * @export
 * @interface ErrorLog
 */
export interface ErrorLog {
    /**
     * 
     * @type {number}
     * @memberof ErrorLog
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorLog
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'errorType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'errorMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'stackTrace'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'requestUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'requestMethod'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorLog
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'ipAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'userAgent'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'severity'?: ErrorLogSeverityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorLog
     */
    'resolved'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorLog
     */
    'resolvedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorLog
     */
    'resolvedBy'?: number;
}

export const ErrorLogSeverityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;

export type ErrorLogSeverityEnum = typeof ErrorLogSeverityEnum[keyof typeof ErrorLogSeverityEnum];


