/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Event
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'endTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'location'?: string;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    'organizerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    'campusId'?: number;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    'maxParticipants'?: number;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    'currentParticipants'?: number;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'status'?: EventStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    'viewCount'?: number;
}

export const EventStatusEnum = {
    Upcoming: 'UPCOMING',
    Ongoing: 'ONGOING',
    Ended: 'ENDED',
    Cancelled: 'CANCELLED'
} as const;

export type EventStatusEnum = typeof EventStatusEnum[keyof typeof EventStatusEnum];


