/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Campus } from './campus';
// May contain unused imports in some cases
// @ts-ignore
import type { Category } from './category';
// May contain unused imports in some cases
// @ts-ignore
import type { GoodsTag } from './goods-tag';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Goods
 */
export interface Goods {
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Goods
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'categoryId'?: number;
    /**
     * 
     * @type {Category}
     * @memberof Goods
     */
    'category'?: Category;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'sellerId'?: number;
    /**
     * 
     * @type {User}
     * @memberof Goods
     */
    'seller'?: User | null;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'campusId'?: number;
    /**
     * 
     * @type {Campus}
     * @memberof Goods
     */
    'campus'?: Campus | null;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'status'?: GoodsStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'viewCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'favoriteCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'stock'?: number;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'soldCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Goods
     */
    'originalPrice'?: number;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'condition'?: string;
    /**
     * 
     * @type {string}
     * @memberof Goods
     */
    'deliveryMethod'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Goods
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof Goods
     */
    'extraAttrs'?: { [key: string]: object; };
    /**
     * 
     * @type {Array<GoodsTag>}
     * @memberof Goods
     */
    'goodsTags'?: Array<GoodsTag>;
    /**
     * 
     * @type {boolean}
     * @memberof Goods
     */
    'approved'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Goods
     */
    'sold'?: boolean;
}

export const GoodsStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Sold: 'SOLD',
    Offline: 'OFFLINE'
} as const;

export type GoodsStatusEnum = typeof GoodsStatusEnum[keyof typeof GoodsStatusEnum];


