/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LogisticsTrackRecord } from './logistics-track-record';

/**
 * 业务数据载荷
 * @export
 * @interface LogisticsDTO
 */
export interface LogisticsDTO {
    /**
     * 
     * @type {number}
     * @memberof LogisticsDTO
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof LogisticsDTO
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'trackingNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'logisticsCompany'?: LogisticsDTOLogisticsCompanyEnum;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'status'?: LogisticsDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'currentLocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'estimatedDeliveryTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'actualDeliveryTime'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LogisticsDTO
     */
    'isOvertime'?: boolean;
    /**
     * 
     * @type {Array<LogisticsTrackRecord>}
     * @memberof LogisticsDTO
     */
    'trackRecords'?: Array<LogisticsTrackRecord>;
    /**
     * 
     * @type {number}
     * @memberof LogisticsDTO
     */
    'syncCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'lastSyncTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsDTO
     */
    'updatedAt'?: string;
}

export const LogisticsDTOLogisticsCompanyEnum = {
    Shunfeng: 'SHUNFENG',
    Zhongtong: 'ZHONGTONG',
    Yuantong: 'YUANTONG',
    Yunda: 'YUNDA',
    Ems: 'EMS',
    Jingdong: 'JINGDONG',
    Debang: 'DEBANG',
    Shentong: 'SHENTONG'
} as const;

export type LogisticsDTOLogisticsCompanyEnum = typeof LogisticsDTOLogisticsCompanyEnum[keyof typeof LogisticsDTOLogisticsCompanyEnum];
export const LogisticsDTOStatusEnum = {
    Pending: 'PENDING',
    PickedUp: 'PICKED_UP',
    InTransit: 'IN_TRANSIT',
    Delivering: 'DELIVERING',
    Delivered: 'DELIVERED',
    Rejected: 'REJECTED',
    Lost: 'LOST'
} as const;

export type LogisticsDTOStatusEnum = typeof LogisticsDTOStatusEnum[keyof typeof LogisticsDTOStatusEnum];


