/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 物流筛选请求参数
 * @export
 * @interface LogisticsFilterRequest
 */
export interface LogisticsFilterRequest {
    /**
     * 搜索关键词
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'keyword'?: string;
    /**
     * 页码（从 0 开始）
     * @type {number}
     * @memberof LogisticsFilterRequest
     */
    'page'?: number;
    /**
     * 每页数量
     * @type {number}
     * @memberof LogisticsFilterRequest
     */
    'size'?: number;
    /**
     * 排序字段
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'sortBy'?: string;
    /**
     * 排序方向
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'sortDirection'?: LogisticsFilterRequestSortDirectionEnum;
    /**
     * 开始时间
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'startTime'?: string;
    /**
     * 结束时间
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'endTime'?: string;
    /**
     * 物流状态（PENDING/IN_TRANSIT/DELIVERED/CANCELLED）
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'status'?: LogisticsFilterRequestStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof LogisticsFilterRequest
     */
    'pageOrDefault'?: number;
    /**
     * 
     * @type {number}
     * @memberof LogisticsFilterRequest
     */
    'sizeOrDefault'?: number;
    /**
     * 
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'sortByOrDefault'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsFilterRequest
     */
    'sortDirectionOrDefault'?: string;
}

export const LogisticsFilterRequestSortDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;

export type LogisticsFilterRequestSortDirectionEnum = typeof LogisticsFilterRequestSortDirectionEnum[keyof typeof LogisticsFilterRequestSortDirectionEnum];
export const LogisticsFilterRequestStatusEnum = {
    Pending: 'PENDING',
    PickedUp: 'PICKED_UP',
    InTransit: 'IN_TRANSIT',
    Delivering: 'DELIVERING',
    Delivered: 'DELIVERED',
    Rejected: 'REJECTED',
    Lost: 'LOST'
} as const;

export type LogisticsFilterRequestStatusEnum = typeof LogisticsFilterRequestStatusEnum[keyof typeof LogisticsFilterRequestStatusEnum];


