/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationResponse
 */
export interface NotificationResponse {
    /**
     * 
     * @type {number}
     * @memberof NotificationResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'type'?: NotificationResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'content'?: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationResponse
     */
    'relatedId'?: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'relatedType'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'link'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'status'?: NotificationResponseStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationResponse
     */
    'emailSent'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'readAt'?: string;
}

export const NotificationResponseTypeEnum = {
    OrderCreated: 'ORDER_CREATED',
    OrderPaid: 'ORDER_PAID',
    OrderCancelled: 'ORDER_CANCELLED',
    OrderCompleted: 'ORDER_COMPLETED',
    GoodsApproved: 'GOODS_APPROVED',
    GoodsRejected: 'GOODS_REJECTED',
    GoodsSold: 'GOODS_SOLD',
    PostReplied: 'POST_REPLIED',
    PostMentioned: 'POST_MENTIONED',
    MessageReceived: 'MESSAGE_RECEIVED',
    FollowSellerNewGoods: 'FOLLOW_SELLER_NEW_GOODS',
    SubscriptionMatchedGoods: 'SUBSCRIPTION_MATCHED_GOODS',
    ReviewReplied: 'REVIEW_REPLIED',
    DisputeSubmitted: 'DISPUTE_SUBMITTED',
    DisputeEscalated: 'DISPUTE_ESCALATED',
    DisputeClosed: 'DISPUTE_CLOSED',
    DisputeResolved: 'DISPUTE_RESOLVED',
    SystemAnnouncement: 'SYSTEM_ANNOUNCEMENT',
    UserBanned: 'USER_BANNED',
    UserUnbanned: 'USER_UNBANNED'
} as const;

export type NotificationResponseTypeEnum = typeof NotificationResponseTypeEnum[keyof typeof NotificationResponseTypeEnum];
export const NotificationResponseStatusEnum = {
    Unread: 'UNREAD',
    Read: 'READ',
    Deleted: 'DELETED'
} as const;

export type NotificationResponseStatusEnum = typeof NotificationResponseStatusEnum[keyof typeof NotificationResponseStatusEnum];


