/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 订单统计数据
 * @export
 * @interface OrderStatisticsDTO
 */
export interface OrderStatisticsDTO {
    /**
     * 总订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'totalOrders'?: number;
    /**
     * 待支付订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'pendingPaymentOrders'?: number;
    /**
     * 已支付订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'paidOrders'?: number;
    /**
     * 已完成订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'completedOrders'?: number;
    /**
     * 已取消订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'cancelledOrders'?: number;
    /**
     * 退款中订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'refundingOrders'?: number;
    /**
     * 已退款订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'refundedOrders'?: number;
    /**
     * 总订单金额（元）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'totalAmount'?: number;
    /**
     * 已完成订单金额（元）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'completedAmount'?: number;
    /**
     * 已退款金额（元）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'refundedAmount'?: number;
    /**
     * 平均订单金额（元）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'averageAmount'?: number;
    /**
     * 订单完成率（%）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'completionRate'?: number;
    /**
     * 订单取消率（%）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'cancellationRate'?: number;
    /**
     * 订单退款率（%）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'refundRate'?: number;
    /**
     * 按订单状态统计（状态 -> 数量）
     * @type {{ [key: string]: number; }}
     * @memberof OrderStatisticsDTO
     */
    'ordersByStatus'?: { [key: string]: number; };
    /**
     * 按支付方式统计金额（支付方式 -> 金额）
     * @type {{ [key: string]: number; }}
     * @memberof OrderStatisticsDTO
     */
    'amountByPaymentMethod'?: { [key: string]: number; };
    /**
     * 按支付方式统计数量（支付方式 -> 数量）
     * @type {{ [key: string]: number; }}
     * @memberof OrderStatisticsDTO
     */
    'countByPaymentMethod'?: { [key: string]: number; };
    /**
     * 今日新增订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'todayNewOrders'?: number;
    /**
     * 今日订单金额（元）
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'todayAmount'?: number;
    /**
     * 今日完成订单数
     * @type {number}
     * @memberof OrderStatisticsDTO
     */
    'todayCompletedOrders'?: number;
}

