/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Campus } from './campus';
// May contain unused imports in some cases
// @ts-ignore
import type { Goods } from './goods';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 业务数据载荷
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'orderNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'goodsId'?: number;
    /**
     * 
     * @type {Goods}
     * @memberof Order
     */
    'goods'?: Goods;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'buyerId'?: number;
    /**
     * 
     * @type {User}
     * @memberof Order
     */
    'buyer'?: User;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'sellerId'?: number;
    /**
     * 
     * @type {User}
     * @memberof Order
     */
    'seller'?: User;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'campusId'?: number;
    /**
     * 
     * @type {Campus}
     * @memberof Order
     */
    'campus'?: Campus | null;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'discountAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'actualAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'status'?: OrderStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'paymentMethod'?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'paymentTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'couponId'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    'cancelled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    'completed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    'paid'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    'pendingPayment'?: boolean;
}

export const OrderStatusEnum = {
    PendingPayment: 'PENDING_PAYMENT',
    Paid: 'PAID',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED',
    Reviewed: 'REVIEWED'
} as const;

export type OrderStatusEnum = typeof OrderStatusEnum[keyof typeof OrderStatusEnum];


