/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 退款统计数据
 * @export
 * @interface RefundStatisticsDTO
 */
export interface RefundStatisticsDTO {
    /**
     * 总退款申请数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'totalRefunds'?: number;
    /**
     * 待审核退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'appliedRefunds'?: number;
    /**
     * 已批准退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'approvedRefunds'?: number;
    /**
     * 已拒绝退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'rejectedRefunds'?: number;
    /**
     * 处理中退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'processingRefunds'?: number;
    /**
     * 已完成退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'completedRefunds'?: number;
    /**
     * 失败退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'failedRefunds'?: number;
    /**
     * 总退款金额（元）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'totalAmount'?: number;
    /**
     * 已完成退款金额（元）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'completedAmount'?: number;
    /**
     * 处理中退款金额（元）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'processingAmount'?: number;
    /**
     * 平均退款金额（元）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'averageAmount'?: number;
    /**
     * 退款批准率（%）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'approvalRate'?: number;
    /**
     * 退款成功率（%）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'successRate'?: number;
    /**
     * 退款失败率（%）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'failureRate'?: number;
    /**
     * 按退款状态统计（状态 -> 数量）
     * @type {{ [key: string]: number; }}
     * @memberof RefundStatisticsDTO
     */
    'refundsByStatus'?: { [key: string]: number; };
    /**
     * 按退款渠道统计金额（渠道 -> 金额）
     * @type {{ [key: string]: number; }}
     * @memberof RefundStatisticsDTO
     */
    'amountByChannel'?: { [key: string]: number; };
    /**
     * 按退款渠道统计数量（渠道 -> 数量）
     * @type {{ [key: string]: number; }}
     * @memberof RefundStatisticsDTO
     */
    'countByChannel'?: { [key: string]: number; };
    /**
     * 今日新增退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'todayNewRefunds'?: number;
    /**
     * 今日退款金额（元）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'todayAmount'?: number;
    /**
     * 今日完成退款数
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'todayCompletedRefunds'?: number;
    /**
     * 平均审核时间（小时）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'avgReviewTime'?: number;
    /**
     * 平均完成时间（小时）
     * @type {number}
     * @memberof RefundStatisticsDTO
     */
    'avgCompletionTime'?: number;
}

