/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RevertRequest
 */
export interface RevertRequest {
    /**
     * 
     * @type {number}
     * @memberof RevertRequest
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RevertRequest
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevertRequest
     */
    'auditLogId': number;
    /**
     * 
     * @type {number}
     * @memberof RevertRequest
     */
    'requesterId': number;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'requesterName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'status': RevertRequestStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof RevertRequest
     */
    'approvedBy'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'approvedByName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'approvedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'approvalComment'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevertRequest
     */
    'revertLogId'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'executedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevertRequest
     */
    'errorMessage'?: string;
}

export const RevertRequestStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Executed: 'EXECUTED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;

export type RevertRequestStatusEnum = typeof RevertRequestStatusEnum[keyof typeof RevertRequestStatusEnum];


