/* tslint:disable */
/* eslint-disable */
/**
 * 校园轻享集市系统 API
 * ## 校园轻享集市系统 RESTful API 文档  基于 Java 21 + Spring Boot 3.x 的企业级单体应用  ### 主要功能 - 用户认证授权（JWT + RBAC） - 二手物品交易 - 订单管理与支付 - 即时通讯（WebSocket） - 论坛社区 - 积分与优惠券系统  ### 技术栈 - Java 21 (Virtual Threads) - Spring Boot 3.2.0 - PostgreSQL 16 - Redis 7.x - JWT 认证  ### 认证说明 大部分接口需要在请求头中携带 JWT Token： ``` Authorization: Bearer <your-jwt-token> ```  ### 获取 Token 1. 调用 `/auth/register` 注册账号 2. 调用 `/auth/login` 登录获取 Token 3. 在后续请求中使用该 Token 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: basui@campus.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户资料响应数据
 * @export
 * @interface UserProfileResponse
 */
export interface UserProfileResponse {
    /**
     * 用户唯一标识
     * @type {number}
     * @memberof UserProfileResponse
     */
    'id'?: number;
    /**
     * 用户名
     * @type {string}
     * @memberof UserProfileResponse
     */
    'username'?: string;
    /**
     * 昵称
     * @type {string}
     * @memberof UserProfileResponse
     */
    'nickname'?: string;
    /**
     * 邮箱（脱敏后）
     * @type {string}
     * @memberof UserProfileResponse
     */
    'email'?: string;
    /**
     * 手机号（脱敏后）
     * @type {string}
     * @memberof UserProfileResponse
     */
    'phone'?: string;
    /**
     * 学号
     * @type {string}
     * @memberof UserProfileResponse
     */
    'studentId'?: string;
    /**
     * 头像地址
     * @type {string}
     * @memberof UserProfileResponse
     */
    'avatar'?: string;
    /**
     * 用户状态
     * @type {string}
     * @memberof UserProfileResponse
     */
    'status'?: string;
    /**
     * 当前积分
     * @type {number}
     * @memberof UserProfileResponse
     */
    'points'?: number;
    /**
     * 校区ID
     * @type {number}
     * @memberof UserProfileResponse
     */
    'campusId'?: number;
    /**
     * 校区名称
     * @type {string}
     * @memberof UserProfileResponse
     */
    'campusName'?: string;
    /**
     * 封禁原因（仅封禁状态时有值）
     * @type {string}
     * @memberof UserProfileResponse
     */
    'banReason'?: string;
    /**
     * 角色列表
     * @type {Array<string>}
     * @memberof UserProfileResponse
     */
    'roles'?: Array<string>;
    /**
     * 注册时间
     * @type {string}
     * @memberof UserProfileResponse
     */
    'createdAt'?: string;
    /**
     * 最后登录时间
     * @type {string}
     * @memberof UserProfileResponse
     */
    'lastLoginAt'?: string;
    /**
     * 个人简介
     * @type {string}
     * @memberof UserProfileResponse
     */
    'bio'?: string;
    /**
     * 信誉分（0-200）
     * @type {number}
     * @memberof UserProfileResponse
     */
    'creditScore'?: number;
    /**
     * 邮箱是否已验证
     * @type {boolean}
     * @memberof UserProfileResponse
     */
    'emailVerified'?: boolean;
    /**
     * 手机号是否已验证
     * @type {boolean}
     * @memberof UserProfileResponse
     */
    'phoneVerified'?: boolean;
    /**
     * 是否启用两步验证
     * @type {boolean}
     * @memberof UserProfileResponse
     */
    'twoFactorEnabled'?: boolean;
}

