/**
 * 权限编码常量（与后端 PermissionCodes 保持一致）
 * @author BaSui
 * @date 2025-11-02
 */

export const PERMISSION_CODES = {
  // ===== 用户与角色 =====
  SYSTEM_USER_VIEW: 'system:user:view',
  SYSTEM_USER_CREATE: 'system:user:create',
  SYSTEM_USER_UPDATE: 'system:user:update',
  SYSTEM_USER_DELETE: 'system:user:delete',
  SYSTEM_USER_BAN: 'system:user:ban',
  SYSTEM_ROLE_ASSIGN: 'system:role:assign',

  // ===== 商品与帖子 =====
  SYSTEM_GOODS_APPROVE: 'system:goods:approve',
  SYSTEM_GOODS_DELETE: 'system:goods:delete',
  SYSTEM_POST_APPROVE: 'system:post:approve',
  SYSTEM_POST_DELETE: 'system:post:delete',

  // ===== 系统与配置 =====
  SYSTEM_CONFIG_UPDATE: 'system:config:update',
  SYSTEM_CONFIG_VIEW: 'system:config:view',
  SYSTEM_STATISTICS_VIEW: 'system:statistics:view',
  SYSTEM_AUDIT_VIEW: 'system:audit:view',
  SYSTEM_RATE_LIMIT_MANAGE: 'system:rate-limit:manage',

  // ===== 校区与分类 =====
  SYSTEM_CAMPUS_MANAGE: 'system:campus:manage',
  SYSTEM_CAMPUS_CROSS: 'system:campus:cross',
  SYSTEM_CATEGORY_MANAGE: 'system:category:manage',
  SYSTEM_TAG_MANAGE: 'system:tag:manage',

  // ===== 合规与举报 =====
  SYSTEM_COMPLIANCE_REVIEW: 'system:compliance:review',
  SYSTEM_REPORT_HANDLE: 'system:report:handle',

  // ===== 市场运营 =====
  MARKET_GOODS_APPROVE: 'market:goods:approve',
  MARKET_ORDER_REFUND: 'market:order:refund',
} as const;

export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const PERMISSION_DESCRIPTIONS: Record<PermissionCode, string> = {
  [PERMISSION_CODES.SYSTEM_USER_VIEW]: '查看用户',
  [PERMISSION_CODES.SYSTEM_USER_CREATE]: '创建用户',
  [PERMISSION_CODES.SYSTEM_USER_UPDATE]: '更新用户',
  [PERMISSION_CODES.SYSTEM_USER_DELETE]: '删除用户',
  [PERMISSION_CODES.SYSTEM_USER_BAN]: '封禁用户',
  [PERMISSION_CODES.SYSTEM_ROLE_ASSIGN]: '分配角色',

  [PERMISSION_CODES.SYSTEM_GOODS_APPROVE]: '审核物品',
  [PERMISSION_CODES.SYSTEM_GOODS_DELETE]: '删除物品',
  [PERMISSION_CODES.SYSTEM_POST_APPROVE]: '审核帖子',
  [PERMISSION_CODES.SYSTEM_POST_DELETE]: '删除帖子',

  [PERMISSION_CODES.SYSTEM_CONFIG_UPDATE]: '修改系统配置',
  [PERMISSION_CODES.SYSTEM_CONFIG_VIEW]: '查看系统配置',
  [PERMISSION_CODES.SYSTEM_STATISTICS_VIEW]: '查看统计看板',
  [PERMISSION_CODES.SYSTEM_AUDIT_VIEW]: '查看审计日志',
  [PERMISSION_CODES.SYSTEM_RATE_LIMIT_MANAGE]: '管理限流规则',

  [PERMISSION_CODES.SYSTEM_CAMPUS_MANAGE]: '管理校区',
  [PERMISSION_CODES.SYSTEM_CAMPUS_CROSS]: '跨校区访问权限',
  [PERMISSION_CODES.SYSTEM_CATEGORY_MANAGE]: '管理分类',
  [PERMISSION_CODES.SYSTEM_TAG_MANAGE]: '管理标签',

  [PERMISSION_CODES.SYSTEM_COMPLIANCE_REVIEW]: '审核隐私请求',
  [PERMISSION_CODES.SYSTEM_REPORT_HANDLE]: '处理用户举报',

  [PERMISSION_CODES.MARKET_GOODS_APPROVE]: '运营商品审核',
  [PERMISSION_CODES.MARKET_ORDER_REFUND]: '处理订单退款',
};

export const ADMIN_DEFAULT_PERMISSIONS: PermissionCode[] = [
  PERMISSION_CODES.SYSTEM_USER_VIEW,
  PERMISSION_CODES.SYSTEM_USER_BAN,
  PERMISSION_CODES.SYSTEM_ROLE_ASSIGN,
  PERMISSION_CODES.SYSTEM_GOODS_APPROVE,
  PERMISSION_CODES.SYSTEM_GOODS_DELETE,
  PERMISSION_CODES.SYSTEM_POST_APPROVE,
  PERMISSION_CODES.SYSTEM_POST_DELETE,
  PERMISSION_CODES.SYSTEM_CONFIG_VIEW,
  PERMISSION_CODES.SYSTEM_CONFIG_UPDATE,
  PERMISSION_CODES.SYSTEM_STATISTICS_VIEW,
  PERMISSION_CODES.SYSTEM_AUDIT_VIEW,
  PERMISSION_CODES.SYSTEM_RATE_LIMIT_MANAGE,
  PERMISSION_CODES.SYSTEM_CAMPUS_MANAGE,
  PERMISSION_CODES.SYSTEM_CAMPUS_CROSS,
  PERMISSION_CODES.SYSTEM_CATEGORY_MANAGE,
  PERMISSION_CODES.SYSTEM_TAG_MANAGE,
  PERMISSION_CODES.SYSTEM_COMPLIANCE_REVIEW,
  PERMISSION_CODES.SYSTEM_REPORT_HANDLE,
  PERMISSION_CODES.MARKET_GOODS_APPROVE,
  PERMISSION_CODES.MARKET_ORDER_REFUND,
];
